source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/lockscreen.jpeg
    blur_passes = 0
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 10%, 5%
    position = 0, 100
    halign = center
    valign = bottom
    hide_input=true

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 3

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    # placeholder_text = Enter Password
    placeholder_text = Level $ATTEMPTS
    check_color = $check_color
    # fail_text = <i>$FAIL ($ATTEMPTS)</i>
    fail_text = -($ATTEMPTS ❤️)

    rounding = 20
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = true
}

